name: debug
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#status
on: status
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: >-
      github.event.state != 'expected' &&
      github.event.state != 'pending'
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
