name: publish
on:
  push:
    tags: [v*.*.*]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run lint
      - run: bun run test
      - run: cd dist && zip ../chrome-extension.zip *
      - run: bun run build
        env:
          FIREFOX_BUILD: 1
      - run: cd dist && zip ../firefox-extension.zip *
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'chrome-extension.zip, firefox-extension.zip'
      - run: gh release create "${{ github.ref_name }}" chrome-extension.zip firefox-extension.zip --draft --generate-notes
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
